version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - MONGO_URI=mongodb+srv://<username>:<password>@cluster0.mongodb.net/<dbname>?retryWrites=true&w=majority

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - backend

